image: ubuntu

before_script:
  - dpkg -S /usr/bin/add-apt-repository
  - apt-get update
  - apt install software-properties-common
  - add-apt-repository universe
  - apt install python3 -y
  - apt install python3-pip -y
  - python3 -V 
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip3 install -r requirements.txt
  - pip3 install -e .
  - apt install xvfb

test:
    script: 
        - pip3 install pytest
        - pytest tests.py
